algoritmo "semnome"
// Função :
// Autor :
// Data : 16/04/2016
// Seção de Declarações 
var
num1,num2:real
inicio
// Seção de Comandos 
escreval("Digite o primeiro numero:")
leia(num1)
escreval("Digite o primeiro numero:")
leia(num2)
escreval("-------------------------------------------")
escreval(num1," +",num2," =",num1+num2)
escreval(num1," -",num2," =",num1-num2)
escreval(num1," /",num2," =",num1/num2)
escreval(num1," x",num2," =",num1*num2)
fimalgoritmo
