algoritmo "semnome"
// Função :
// Autor :
// Data : 16/04/2016
// Seção de Declarações 
var
Comprimento,largura,carpete,valor:real
inicio
// Seção de Comandos
valor<-40.00
escreval("Digite o Comprimento:")
leia(comprimento)
escreval("Digite o largura:")
leia(largura)
escreval("Você precisará de",comprimento*largura," metros de carpete.")
escreval("O custo total será de R$",(comprimento*largura)*valor,".")
fimalgoritmo
