algoritmo "semnome"
// Função :
// Autor :
// Data : 16/04/2016
// Seção de Declarações 
var
bim1,bim2,bim3,bim4:real
nome:caracter
inicio
// Seção de Comandos 
escreval("Digite o nome do Aluno:")
leia(nome)
escreval("Nota do 1º Bim:")
leia(bim1)
escreval("Nota do 2º Bim:")
leia(bim2)
escreval("Nota do 3º Bim:")
leia(bim3)
escreval("Nota do 4º Bim:")
leia(bim4)
escreval("Nome do aluno: ",nome)
escreval("Média do Aluno: ",(bim1+bim2+bim3+bim4)/4,".")


fimalgoritmo
