algoritmo "semnome"
// Função :
// Autor :
// Data : 23/04/2016
// Seção de Declarações 
var
tamanho,velocidade:real
inicio
// Seção de Comandos
escreval("Conversor de Downloads em bits")
escreval("Digite o tamanho do arquivo:")
leia(tamanho)
escreval("Digite a velocidade da conexão:")
leia(velocidade)
escreval("O tempo estimado para download é de",tamanho/velocidade," segundos.")




                                                                   s

fimalgoritmo
