algoritmo "semnome"
// Função :
// Autor :
// Data : 23/04/2016
// Seção de Declarações 
var
num1,num2:numerico
inicio
// Seção de Comandos 
escreval("Informe o 1º Numero")
leia(num1)
escreval("Informe o 2º Numero")
leia(num2)

se num1 = num2 entao
alerta<-"os numeros são iguais"
se num1 > num2 entao
escreval(num1," é maior que",num2)
senao
escreval (num1," é menor que",num2)
fimse
fimse
fimalgoritmo

