algoritmo "Someosvalores"
// Função :
// Autor :
// Data : 19/03/2016
// Seção de Declarações 
var
produto: caracter
quant:inteiro
Valor, parc3x, valor3x,parc6x, valor6x: real


inicio
// Seção de Comandos
parc3x <-3
parc6x <-6
escreva("Produto: ")
leia(produto)
escreva("Quantidade: ")
leia(quant)
escreva("Valor total do investimento:")
leia(valor)
escreval("----------------------------------------")
escreval("Valor em 3x.")
escreval(valor/parc3x)
escreval("Valor em 6x.")
escreval(valor/parc6x)
fimalgoritmo
